### ISSUE TITLE
文字エンコーディングを UTF-8 に

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/www.mozilla-japan.org#1]
GitHub のオンラインエディタで編集できるようにするためには UTF-8 である必要があるし、一般的に UTF-8 で統一していた方が楽なので一括で UTF-8 にしてしまいたい。

nkf コマンド実行するだけじゃなくて meta タグや css の @charset 規則などの書き換えを伴うので要注意。

**Comment by kyoshino** [comment]
手間もかかるので、現状のコンテンツはそのまま放置で。
