### ISSUE TITLE
MPL 参考和訳を mozilla.org or mozilla.jp に移動

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/www.mozilla-japan.org#10]
mozilla-japan.org 自体を終息させる方向であれば以下で公開している MPL 1.1 参考和訳などについてもどこかに移動して残しておきたい:

https://www.mozilla-japan.org/MPL/

mozilla.org で MPL 1.1 についてはこちらで公開している:
https://www.mozilla.org/en-US/MPL/historical/

**Comment by kyoshino** [comment]
www.mozilla-japan.org は廃止となりました。(#14)

MPL 2.0 の公開から 6 年経過してて、今から旧バージョンの翻訳だけ残してもあまり意味がないと思うので、WONTFIX で閉じます。
