### ISSUE TITLE
www.mozilla-japan.org が Server Not Found

### ISSUE THREAD

**Issue by kyoshino** [mozilla-japan/www.mozilla-japan.org#14]
@baffclan さんが [Bug 1406361](https://bugzilla.mozilla.org/show_bug.cgi?id=1406361) で報告してくれていますが、現在 www.mozilla-japan.org が Server Not Found で到達不能になっています。いずれ廃止することにはなると思いますが、今のところは不具合だと思うので、確認お願いできますか？ @kudodo @dynamis

**Comment by kudodo** [comment]
@kyoshino さん、www.mozilla-japan.org ですが、契約により12月31日をもってドメインがMoCo管理になっています。DNS的に解決できない状態ですので、正常な状態です。
mozilla.jpは日本のコミュニティで管理できているのですがmozilla-japan.orgは利用不可です。

コンテンツその物はコミュニティサーバ203.104.96.245に残っているので、www.mozilla.jp/mozilla-japanあたりにごっそり引越をするか、もしくはwww2.mozilla.jp等としてコミュニティサーバでvirtual hostするかどちらかになりますが、コンテンツのURLが変わることは避けられません。
またリダイレクトさせるのはドメインを操作する権限を持っていないので、MoCoと相談になります。

**Comment by kyoshino** [comment]
それなら仕方ないですね。コンテンツもずっとセキュリティアドバイザリぐらいしか更新してなくて、その更新も 7 月で止めたので、大きな影響はないでしょう。WONTFIX で閉じて、このレポジトリもアーカイブしちゃいますね。
