### ISSUE TITLE
update /foundation/trademarks/list.html

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/www.mozilla-japan.org#6]
多分ちょっと古い:
http://www.mozilla.org/foundation/trademarks/list.html
http://www.mozilla-japan.org/foundation/trademarks/list.html

**Comment by kyoshino** [comment]
商標ポリシーは https://github.com/mozilla-japan/www.mozilla-japan.org/commit/9dcc65425aac71e7a30dc3ffee583c5d421358e4 で .org へ移動しました。
